services:
  - type: web
    name: taxagent-pro
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: taxagent-data
      mountPath: /tmp
      sizeGB: 1 