services:
  - type: web
    name: taxagent-pro
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        python3-dev \
        libmupdf-dev \
        libfreetype6-dev \
        libharfbuzz-dev \
        libfribidi-dev \
        libjpeg-dev \
        libopenjp2-7-dev \
        libpng-dev \
        libtiff-dev \
        libxcb1-dev \
        libzstd-dev \
        gcc \
        g++
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: taxagent-data
      mountPath: /tmp
      sizeGB: 1 